name = "GradedArraysNext"
uuid = "6ca31247-5036-4cc6-95db-9b8b909db17f"
authors = ["ITensor developers <support@itensor.org> and contributors"]
version = "0.1.2"

[deps]
BlockSparseArrays = "2c9a651f-6452-4ace-a6ac-809f4280fbb4"
DiagonalArrays = "74fd4be6-21e2-4f6f-823a-4360d37c7a77"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
KroneckerArrays = "05d0b138-81bc-4ff7-84be-08becefb1ccc"
TensorAlgebra = "68bd88dc-f39d-4e12-b2ca-f046b68fcc6a"
TensorProducts = "decf83d6-1968-43f4-96dc-fdb3fe15fc6d"

[compat]
BlockSparseArrays = "0.8.1"
DiagonalArrays = "0.3.10"
FillArrays = "1.13.0"
KroneckerArrays = "0.1.26"
TensorAlgebra = "0.3.10"
TensorProducts = "0.1.7"
julia = "1.10"
