name = "GradedArraysNext"
uuid = "6ca31247-5036-4cc6-95db-9b8b909db17f"
authors = ["ITensor developers <support@itensor.org> and contributors"]
version = "0.1.1"

[deps]
KroneckerArrays = "05d0b138-81bc-4ff7-84be-08becefb1ccc"

[compat]
KroneckerArrays = "0.1.26"
julia = "1.10"
